spring:
  application:
    name: mg-clog-be
  thymeleaf:
    cache: false
  data:
    mongodb:
      database: clog
      host: localhost
      port: 27017
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
springdoc:
  show-actuator: true
clog:
  jwtSecret: footballSecretKey
  jwtExpirationMs: 8640000
  security-mapping:
    '[aigner.georg.79@gmail.com]':
      - ROLE_USER
      - ROLE_ADMIN
    '[aigner.christina.83@gmail.com]':
      - ROLE_USER
    '[mg4code@gmail.com]':
      - ROLE_USER
